export AUTH0_DOMAIN='dev-n2b3c216vvhww5je.us.auth0.com'
export API_IDENTIFIER='your-api-identifier'
export AUTH0_CLIENT_ID='jkplYa7wJNDYAkCB82RqdErnjRR7Naex'
export AUTH0_CLIENT_SECRET='QZWoaiHxC46zqOR_O3jYvt3Cw5kqJXXtdojr18NTafQqoakky5T9TYvDJP2j_ZhE'